USE master
/*VERITABANI OLUSTURULDU*/
CREATE DATABASE OrnekDB

USE OrnekDB

/*TABLOLAR OLUSTURULDU*/
CREATE TABLE USERS
(
ID INT IDENTITY(1,1),
USERNAME_ VARCHAR(50),
PASSWORD_  VARCHAR(50),
NAMESURNAME VARCHAR(100),
EMAIL VARCHAR(100),
GENDER VARCHAR(1),
BIRTHDATE DATE,
CREATEDATE DATETIME,
TELNR1 VARCHAR(15),
TELNR2 VARCHAR(15)
CONSTRAINT PK_USERS PRIMARY KEY CLUSTERED (ID ASC)
)
CREATE TABLE ITEMS
(
  ID INT IDENTITY(1,1),
  ITEMCODE VARCHAR(50),
  ITEMNAME VARCHAR(100),
  UNITPRICE FLOAT,
  CATEGORY1 VARCHAR(50),
  CATEGORY2 VARCHAR(50),
  CATEGORY3 VARCHAR(50),
  CATEGORY4 VARCHAR(50),
  BRAND VARCHAR(50)
  CONSTRAINT PK_ITEMS PRIMARY KEY CLUSTERED (ID ASC)
)
CREATE TABLE PAYMENTS
(
  ID INT IDENTITY(1,1),
  ORDERID INT,
  PAYMENTTYPE TINYINT,
  DATE_ DATETIME,
  ISOK BIT,
  APPROVECODE VARCHAR(100),
  PAYMENTTOTAL FLOAT
  CONSTRAINT PK_PAYMENTS PRIMARY KEY CLUSTERED (ID ASC)
)
CREATE TABLE ADRESS
(
   ID INT IDENTITY(1,1),
   USERID INT,
   COUNTRYID TINYINT,
   CITYID SMALLINT,
   TOWNID INT,
   DISTRICTID INT,
   POSTALCODE VARCHAR(10),
   ADRESSTEXT VARCHAR(500)
   CONSTRAINT PK_ADRESS PRIMARY KEY CLUSTERED (ID ASC)
)
CREATE TABLE ORDERS
( 
   ID INT IDENTITY(1,1),
   USERID INT,
   DATE_ DATETIME,
   TOTALPRICE FLOAT,
   STATUS_ TINYINT,
   ADRESSID INT
   CONSTRAINT PK_ORDERS PRIMARY KEY CLUSTERED (ID ASC)
)
CREATE TABLE ORDERDETAILS
( 
   ID INT IDENTITY(1,1),
   ORDERID INT,
   ITEMID INT,
   AMOUNT INT,
   UNITPRICE FLOAT,
   LINETOTAL FLOAT,
   CONSTRAINT PK_ORDERDETAILS PRIMARY KEY CLUSTERED (ID ASC)
)
CREATE TABLE COUNTRIES
(
ID TINYINT IDENTITY(1,1),
COUNTRY VARCHAR(50)
CONSTRAINT PK_COUNTRIES PRIMARY KEY CLUSTERED(ID ASC)
)
CREATE TABLE CITIES
(  
  ID SMALLINT IDENTITY(1,1),
  COUNTRYID TINYINT,
  CITY VARCHAR(50)
  CONSTRAINT PK_CITIES PRIMARY KEY CLUSTERED (ID ASC)
)
CREATE TABLE TOWNS
(  
  ID SMALLINT IDENTITY(1,1),
  CITYID TINYINT,
  TOWN VARCHAR(50)
  CONSTRAINT PK_TOWNS PRIMARY KEY CLUSTERED (ID ASC)
)
CREATE TABLE DISTRICTS
(  
  ID SMALLINT IDENTITY(1,1),
  TOWNID TINYINT,
  DISTRICT VARCHAR(50)
  CONSTRAINT PK_DISTRICT PRIMARY KEY CLUSTERED (ID ASC)
)
CREATE TABLE INVOICES
(
  ID INT IDENTITY(1,1),
  ORDERID INT,
  DATE_ DATETIME,
  ADRESSID INT,
  CARGOFISCHENO VARCHAR(20),
  TOTALPRICE FLOAT
  CONSTRAINT PK_INVOICES PRIMARY KEY CLUSTERED (ID ASC) 
)
CREATE TABLE INVOICESDETAILS
(
  ID INT IDENTITY(1,1),
  INVOICEID INT,
  ORDERDETAILID INT,
  ITEMID INT,
  AMOUNTID INT,
  UNITPRICE FLOAT,
  LINETOTAL FLOAT
  CONSTRAINT PK_INVOICESDETAILS PRIMARY KEY CLUSTERED (ID ASC) 
)

/*VERI GIRISLERI YAPILDI*/
INSERT INTO USERS VALUES('hsynaatik','15975300','Hüseyin Atýk','hsynaatik@gmail.com','E','2002-05-25','','5442239645','5442239637')
INSERT INTO USERS VALUES('DENEME','15975300','DENEME Atýk','deneme@gmail.com','K','2002-05-25','','5362239675','5374529631')

INSERT INTO COUNTRIES VALUES('TURKIYE')
INSERT INTO COUNTRIES VALUES('ALMANYA')

INSERT INTO CITIES VALUES(1,'ANKARA')
INSERT INTO CITIES VALUES(1,'BURSA')
INSERT INTO CITIES VALUES(1,'ÝSTANBUL')

INSERT INTO TOWNS VALUES(1,'MAMAK')
INSERT INTO TOWNS VALUES(2,'ÝZNÝK')
INSERT INTO TOWNS VALUES(3,'PENDÝK')

INSERT INTO DISTRICTS VALUES(1,'YENÝMAHALLE')
INSERT INTO DISTRICTS VALUES(2,'YESÝLCAMÝÝ')
INSERT INTO DISTRICTS VALUES(3,'TOPKAPI')

INSERT INTO ADRESS VALUES(2,1,2,1,1,'1524','ANKARA MAMAK')
INSERT INTO ADRESS VALUES(1,1,2,2,2,'16860','BURSA ÝZNÝK')

INSERT INTO ORDERS VALUES(1,'2023-04-26',84.75,1,2)
INSERT INTO ORDERS VALUES(2,'2023-05-13',96.75,1,1)

INSERT INTO ITEMS VALUES(01,'GÖMLEK',81.35,'ERKEK','ÜST GÝYÝM','PAMUK','GÖMLEK','PUMA')
INSERT INTO ITEMS VALUES(02,'AYAKKABI',89.43,'ERKEK','ALT GÝYÝM','SPOR','BEYAZ','NIKE')

INSERT INTO INVOICES VALUES(1,'2023-04-26',1,'GO1542',84.75)
INSERT INTO INVOICES VALUES(2,'2023-05-13',2,'AY1254',96.75)

INSERT INTO PAYMENTS VALUES(2,2,'2023-05-13',1,'OK652',96.75)

INSERT INTO ORDERDETAILS VALUES(1,1,2,84.75,90.15)

INSERT INTO INVOICESDETAILS VALUES(1,1,2,1,84.75,90.15)

/*TABLOLAR LISTELENDI*/
SELECT*FROM INVOICESDETAILS
SELECT*FROM ORDERDETAILS
SELECT*FROM PAYMENTS
SELECT*FROM INVOICES
SELECT*FROM ITEMS
SELECT*FROM ORDERS
SELECT*FROM ADRESS
SELECT*FROM DISTRICTS
SELECT *FROM TOWNS
SELECT *FROM CITIES
SELECT*FROM COUNTRIES
SELECT*FROM USERS

SELECT U.USERNAME_,U.EMAIL,A.ADRESSTEXT, C.COUNTRY, CT.CITY, T.TOWN FROM
USERS U
JOIN ADRESS A ON A.USERID=U.ID
JOIN COUNTRIES C ON C.ID=A.COUNTRYID
JOIN CITIES CT ON CT.ID=A.CITYID
JOIN TOWNS T ON T.ID=A.TOWNID

SELECT CT.CITY,COUNT(U.ID) AS KULLANICISAYISI FROM
USERS U
JOIN ADRESS A ON A.USERID=U.ID
JOIN COUNTRIES C ON C.ID=A.COUNTRYID
JOIN CITIES CT ON CT.ID=A.CITYID
JOIN TOWNS T ON T.ID=A.TOWNID
GROUP BY CT.CITY

--JOIN 
/*ORTAK VERILER GELDI*/
SELECT U.ID, U.USERNAME_, A.ADRESSTEXT FROM 
USERS U
JOIN
ADRESS A ON A.USERID=U.ID

--LEFT JOIN
/*SOL TARAFDAKI(USER TABLOSU) TABLONUN TUM VERILERI GELDI */
SELECT U.ID, U.USERNAME_, A.ADRESSTEXT FROM 
USERS U
LEFT JOIN
ADRESS A ON A.USERID=U.ID

--RIGHT JOIN
/*SAG TARAFDAKI(ADRESS TABLOSU) TABLONUN TUM VERILERI GELDI */
SELECT U.ID, U.USERNAME_, A.ADRESSTEXT FROM 
USERS U
RIGHT JOIN
ADRESS A ON A.USERID=U.ID

--FULL JOIN
/*IKI TABLODAKI TUM VERILER GELIR*/
SELECT U.ID, U.USERNAME_, A.ADRESSTEXT FROM 
USERS U
FULL JOIN
ADRESS A ON A.USERID=U.ID

--KULLANICI ADI SOYADI ÝL ÝLÇE SEMT ACIK ADRES SÝPARÝS ID TARÝH TOPLAM TUTAR ODEME TARIHI BANKA ONAY KODU   FATURA TARÝHÝ   KARGO FÝS 
SELECT 
U.USERNAME_ AS KULLANICIADI, U.NAMESURNAME AS ADSOYAD,
CT.CITY IL, T.TOWN ILCE ,
D.DISTRICT AS SEMT, 
A.ADRESSTEXT  ACIKADRES, O.ID AS SIPRAISID, O.DATE_ AS TARIH,
O.TOTALPRICE TOPLAMTUTAR,P.DATE_ AS ODEMETARIHI, P.APPROVECODE AS BANKAONAYKODU,
I.DATE_ AS FATURATARIHI,I.CARGOFISCHENO AS KARGOFISNO

FROM ORDERS O
INNER JOIN USERS U ON U.ID=O.USERID
INNER JOIN ADRESS A ON A.ID=O.ADRESSID
INNER JOIN CITIES CT ON CT.ID=A.CITYID
INNER JOIN TOWNS T ON T.ID=A.TOWNID
INNER JOIN DISTRICTS D ON D.ID=A.DISTRICTID
INNER JOIN PAYMENTS P ON P.ORDERID=O.ID
INNER JOIN INVOICES I ON I.ORDERID=O.ID
