USE ETradeDB

--CREATE TABLE CUSTOMERS, CUSTOMERS TABLOSU OLUSTURULDU
SELECT*
FROM
CUSTOMERS



/* tabloya veri ekleme*/
INSERT INTO CUSTOMERS VALUES('HakkI ÖGren','Gaziantep','1986-04-12','ÞehitKamil','E')

/* Tabloda veri güncelleme*/
UPDATE CUSTOMERS SET Nation='TR',Age=DATEDIFF(YEAR,BirthDate,GETDATE())

/*Tablodaki Verileri Siler yeni veri eklendiðinde otomatik artan Id i KALDIGI yerden baslar*/
DELETE FROM CUSTOMERS
/*Tablodaki tüm verileri siler yeni veri eklendiðinde Id i 1den baslar*/
TRUNCATE TABLE CUSTOMERS


SELECT * FROM CUSTOMERS
WHERE Age>=40

SELECT *FROM CUSTOMERS
WHERE BirthDate BETWEEN '1990' AND '1999'



  /*DISTINCT tekrar eden SATIRLARI TEKILESTIRIR.*/
  SELECT DISTINCT Age From CUSTOMERS


  /*ORDER BY SIRALAMA komutu
    ASC KUCUK TEN BUYUGE SIRALAMA
	DESC BUYUKTEN KUCUGE SIRLAMA
    */
  SELECT *FROM CUSTOMERS ORDER BY CustomerName asc
   
   /*AGGREGATE FUNCTIONS*/
   /*SELECT 
     SUM,COUNT, MIN, MAX, AVG FROM TABLOADI
	 AVG =ortalama
	 */

/*ASCII*/
SELECT ASCII('B')
/*CHAR FONKSIYONLARI*/
SELECT CHAR(66)

/*concat*/
SELECT CONCAT('HÜSEYİN','ATIK')

/*T-SQL DEGISKEN TANIMLAMA*/
DECLARE @ISIM AS VARCHAR(100)
SET @ISIM='HUSEYIN ATIK'
SELECT @ISIM

DECLARE 
@SAYI AS INT,
@SAYI2 AS INT,
@TOPLAM AS INT

SET @SAYI=35
SET @SAYI2=12
SET @TOPLAM=@SAYI+@SAYI2

SELECT @SAYI SAYI1,@SAYI2 SAYI2,@TOPLAM AS TOPLAM

DECLARE @TARIH AS DATETIME
SET @TARIH =GETDATE()
SELECT @TARIH AS TARIH

/*SUBSTRİNG*/
DECLARE @STRİNG VARCHAR(50)
SET @STRİNG='HUSEYIN ATIK'
SELECT SUBSTRING(@STRİNG,6,4)

/*LOWER BIR STRING IFADEYI KUCUK HARFLERE CEVIRIR.
  UPPER BIR STRING IFADEYI BUYUK HARFLERE CEVIRIR.*/
DECLARE @STRİNG1 VARCHAR(50),
@STRİNG2 VARCHAR(50)
SET @STRİNG1='HUSEYIN ATIK'
SET @STRİNG2='hüseyin atık'
SELECT LOWER(@STRİNG1) as lower ,UPPER(@STRİNG2) as upper


--Date Fonksiyonlari--

--DATEADD 
DECLARE @DATE_ AS DATETIME 
SET @DATE_='2023-05-25 16:21:37'
DECLARE @TARIH1 AS DATETIME
SET @TARIH1=DATEADD(DAY,1,@DATE_)
SELECT @DATE_ AS BUGUN ,@TARIH1 AS YARIN

--DATEDIFF
DECLARE @DATE_ AS DATETIME 
SET @DATE_='2023-05-25 16:21:37'
DECLARE @TARIH1 AS DATETIME
SET @TARIH1='2024-10-28 14:20:08'
SELECT DATEDIFF(YEAR,@DATE_,@TARIH1) ARADAKI_YIL_FARKI
SELECT DATEDIFF(MONTH,@DATE_,@TARIH1) ARADAKI_AY_FARKI

--DATEFROMPARTS  TARIH FORMATINA DONUSTURUR
SELECT DATEFROMPARTS(2023,04,27)

/*T-SQL DONGULER
  *FOR DONGUSU YOKTUR
  -WHILE DONGUSU VARDIR
*/
--WHILE DONGUSU
DECLARE @I AS INT=0
WHILE @I<10
BEGIN
PRINT @I
SET @I=@I+1
END

SELECT * FROM NAMES
SELECT*FROM SURNAMES
SELECT*FROM PERSONS

DECLARE @NAME VARCHAR(50),
        @SURNAME VARCHAR(50),
        @GENDER VARCHAR(1),
        @BIRTHDATE DATETIME,
        @AGE INT, 
        @AGEGROUP VARCHAR(50)

    WHILE @I<1
	BEGIN
	SELECT @NAME=NAMES,@GENDER=GENDER  FROM NAMES WHERE ID= ROUND(RAND()*11,0)
	SELECT @SURNAME=SURNAME FROM SURNAMES WHERE ID= ROUND(RAND()*11,0)
	SELECT @NAME,@GENDER,@SURNAME

	SET @I=I+1
	END

	/*tablo ile ilgili bilgiler*/
	SP_SPACEUSED 'NAMES'