/*DATABES VE TABLES SCRÝPT*/
USE [HRDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[WORKERS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[WORKERCODE] [varchar](20) NULL,
	[WORKERNAME] [varchar](100) NULL,
	[GENDER] [varchar](1) NULL,
	[BIRTHDATE] [date] NULL,
	[TCNO] [varchar](11) NULL,
	[WORKERBORCODE] [uniqueidentifier] NULL,
 CONSTRAINT [PK_WORKERS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[WORKERTRANSACTIONS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[WORKERID] [int] NULL,
	[DATE_] [datetime] NULL,
	[IOTYPE] [varchar](1) NULL,
	[GATEID] [int] NULL,
 CONSTRAINT [PK_WORKERTRANSACTIONS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


INSERT INTO WORKERS VALUES('12345678901','Huseyin Atik','E','20020525','12345678901',NEWID())

SELECT*FROM WORKERS
SELECT*FROM WORKERTRANSACTIONS

INSERT INTO WORKERTRANSACTIONS VALUES (1,'2023-08-04 09:00:35','G',2)
INSERT INTO WORKERTRANSACTIONS VALUES (1,'2023-08-04 12:00:48','C',1)
INSERT INTO WORKERTRANSACTIONS VALUES (1,'2023-08-04 13:05:38','G',3)


/*KART KONTROL PROCEDURE*/
ALTER PROCEDURE SP_CARD_CONTROL
@WORKERBORCODE AS VARCHAR(50)
AS
BEGIN
  DECLARE @WORKERNAME AS VARCHAR(100)
  SELECT @WORKERNAME=WORKERNAME FROM WORKERS WHERE WORKERBORCODE= @WORKERBORCODE
  IF @WORKERNAME IS NULL
   BEGIN
   RAISERROR('KART GECERSIZ!',16,1)
   RETURN
   END 
   ELSE 
   BEGIN
   SELECT @WORKERNAME
   END
  
END
EXEC SP_CARD_CONTROL @WORKERBORCODE='7685BB4B-4FA7-4FAB-8262-C51ECD0457A4'

/*CALISAN GIRIS-CIKIS PROCEDURE*/
CREATE  PROC SP_WORKER_INOUT
@WORKERBORCODE AS VARCHAR(50),
@DATE AS DATETIME,
@IOTYPE AS VARCHAR(1),
@GATEID AS INT
AS
BEGIN 
    DECLARE @WORKERNAME AS VARCHAR(100)
	DECLARE @WORKERID AS INT
	SELECT @WORKERNAME=WORKERNAME,@WORKERID=ID FROM WORKERS
	WHERE @WORKERBORCODE=WORKERBORCODE

	IF @WORKERID IS NULL
	BEGIN
	     RAISERROR('OKUTULAN KART GECERSIZ',16,1)
		 RETURN
    END
    
	DECLARE @LASTIO AS VARCHAR(1)
	SELECT TOP 1 @LASTIO=IOTYPE FROM WORKERTRANSACTIONS 
	WHERE WORKERID=1 AND DATE_>=CONVERT(DATE,GETDATE())
	ORDER BY DATE_ DESC

	IF @LASTIO=@IOTYPE
  BEGIN 
	IF @IOTYPE='G'
	BEGIN
	     RAISERROR('ZATEN ICERIDE GORUNUYORSUNUZ,GIRIS YAPAMAZSINIZ',16,1)
		 RETURN
	END
	IF @IOTYPE='C'
	BEGIN
	     RAISERROR('ZATEN DISARIDA GORUNUYORSUNUZ,CIKIS YAPAMAZSINIZ',16,1)
		 RETURN
	END
   END
INSERT INTO WORKERTRANSACTIONS VALUES(@WORKERID,@DATE,@IOTYPE,@GATEID)
SELECT @WORKERNAME AS WORKENAME,@DATE AS DATE_ , @IOTYPE AS IOTYPE
END

TRUNCATE TABLE WORKERTRANSACTIONS
SELECT *FROM WORKERTRANSACTIONS
SELECT*FROM WORKERS

EXEC SP_WORKER_INOUT '7685BB4B-4FA7-4FAB-8262-C51ECD0457A4','2023-04-28 17:50:15','C',6