
DECLARE @ITEMID AS INT
DECLARE @DATE AS DATETIME
DECLARE @AMOUNT AS INT
DECLARE @IOTTYPE AS SMALLINT

SET @ITEMID=ROUND(RAND()*4,0)
IF @ITEMID=0
   SET @ITEMID=1

   SET @DATE =DATEADD(DAY,-ROUND(RAND()*365,0),GETDATE())
   SET @AMOUNT=ROUND(RAND()*9,0)+1
   SET @IOTTYPE=ROUND(RAND()*1,0)+1

INSERT INTO ITEMTRANSACTIONS
VALUES(@ITEMID,@DATE,@AMOUNT,@IOTTYPE)
SELECT *FROM ITEMTRANSACTIONS

TRUNCATE TABLE ITEMTRANSACTIONS

/*TRIGGER*/

CREATE TRIGGER TRG_TRANSACTION_INSERT
ON ITEMTRANSACTIONS
AFTER INSERT
AS
BEGIN 
END
