CREATE DATABASE HOLLYWOODSTARSDB

USE HOLLYWOODSTARSDB

CREATE TABLE HOLLYWOODSTARS
(
   ID INT IDENTITY(1,1),
   GENDER VARCHAR(1),
   NAME_ VARCHAR(50),
   SURNAME VARCHAR(50),
   CONSTRAINT PK_HOLLYWOODSTARS PRIMARY KEY CLUSTERED (ID ASC)
)

INSERT INTO HOLLYWOODSTARS VALUES('M','RUSSEL','CROWE')
INSERT INTO HOLLYWOODSTARS VALUES('M','GEORGE','LUCAS')
INSERT INTO HOLLYWOODSTARS VALUES('M','MARK','HAMILL')
INSERT INTO HOLLYWOODSTARS VALUES('M','HARNISON','FORD')
INSERT INTO HOLLYWOODSTARS VALUES('F','CARRIE','FISHER')
INSERT INTO HOLLYWOODSTARS VALUES('M','PETER','CUSHING')
INSERT INTO HOLLYWOODSTARS VALUES('M','ANTHONY','STANTON')
INSERT INTO HOLLYWOODSTARS VALUES('F','ELLEN','DEGENERES')

SELECT*FROM HOLLYWOODSTARS

/*STRING FONKSIYON ALISTIRMALARI*/
/*BU TABLOYA YENI , NAMESURNAME ISIMLI BIR ALAN EKLEYINIZ VE BU ALANI NAME VE SURNAME ALANLARINI BIRLESTIREREK GUNCELLEYINIZ*/

ALTER TABLE HOLLYWOODSTARS ADD NAMESURNAME VARCHAR(100)
UPDATE HOLLYWOODSTARS SET NAMESURNAME= NAME_+' '+SURNAME

/*ISIM SOYISMI ALT ALTA GETIRME*/
SELECT 'ISIM:'+NAME_+CHAR(13)+'SOYISIM:'+SURNAME
FROM HOLLYWOODSTARS
WHERE ID=1

/*ISIM LERI BUYUK HARFDEN KUCUK HARFE CEVIRME*/

UPDATE HOLLYWOODSTARS SET NAME_=LOWER(NAME_)
SELECT * FROM HOLLYWOODSTARS

/*ISIM LERI KUCUK HARFDEN BUYUK HARFE CEVIRME*/

UPDATE HOLLYWOODSTARS SET NAME_=UPPER(NAME_)
SELECT * FROM HOLLYWOODSTARS

CREATE TABLE ORNEK(
 ID INT IDENTITY(1,1),
 NAMESURNAME VARCHAR(100),
 EMAIL VARCHAR(100)
 CONSTRAINT PK_ORNEK PRIMARY KEY CLUSTERED (ID ASC)
)

INSERT INTO ORNEK VALUES('HUSEYIN ATIK','hsy_atik@gmail.com')
INSERT INTO ORNEK VALUES('MELIKE SARAC','mlk_sarac@yahoo.com')
INSERT INTO ORNEK VALUES('AYHAN KOR','ayh_kor@yahoo.com')
INSERT INTO ORNEK VALUES('FUAT OZBIR','fua_ozbr@yandex.com')
INSERT INTO ORNEK VALUES('OZLEM TEKIN','ozl_tek�n@outlook.com')
INSERT INTO ORNEK VALUES('ALI KUS','ali_kus@linkedn.com')
SELECT *FROM ORNEK

SELECT RIGHT(EMAIL,LEN(EMAIL)-CHARINDEX('@',EMAIL)) SERVISSAGLAYICI,
COUNT(*) MUSTERISAYISI
FROM ORNEK
GROUP BY RIGHT(EMAIL,LEN(EMAIL)-CHARINDEX('@',EMAIL))
ORDER BY 2 DESC
